### ISSUE TITLE
Extensions beyond testcontainers

### ISSUE THREAD

**Issue by dmitry-timofeev** [rnorth/mkdocs-codeinclude-plugin#1]
Hi @rnorth,

Thank you for sharing this plugin! It worked well in a code inclusion prototype for our project documenation. May I ask if you accept contributions extending the plugin functionality beyond the test-containers project requirements? For instance, extra languages support?

**Comment by rnorth** [comment]
Hi @dmitry-timofeev!
Thanks for your interest in this - I'm glad it's been useful for you.

As will be _painfully_ obvious, I only developed this just enough for our bare minimum requirements in Testcontainers and didn't take it any further. I apologise that you've encountered rough edges, and am very grateful that you're interested in improving the plugin.

The answer is yes: please do contribute improvements and fixes as you see fit!
I'm on holiday for the next week, but I will try and review/accept changes the week after.
Thank you
Richard

**Comment by dmitry-timofeev** [comment]
Hi Richard,

Thank you very much for the response and your willingness to accept patches! I hope I'll finish the open ones by then.

Cheers,
Dmitry
