### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by dmitry-timofeev** [rnorth/mkdocs-codeinclude-plugin#2]
Would you please consider adding a license to the project? 

`setup.py` currently specifies MIT in one place and Apache 2.0 in the other:

https://github.com/rnorth/mkdocs-codeinclude-plugin/blob/master/setup.py#L26-L36

**Comment by rnorth** [comment]
🤯 whoops.
Let's go with the MIT licence, then. I'll clarify in a PR; probably next week though.

**Comment by dmitry-timofeev** [comment]
Great, thanks!

**Comment by rnorth** [comment]
Clarified as MIT throughout - sorry for the delay.
